// Planets
export const ADD_PLANETS_LOADING = 'ADD_PLANETS_LOADING'
export const ADD_PLANETS_LOADING_SUCCESS = 'ADD_PLANETS_LOADING_SUCCESS'
export const PLANETS_LOADING = 'PLANETS_LOADING'
export const PLANETS_LOAD_SUCCESS = 'PLANETS_LOAD_SUCCESS'
export const PLANETS_LOAD_ERROR = 'PLANETS_LOAD_ERROR'

// Films
export const ADD_FILMS_LOADING = 'ADD_FILMS_LOADING'
export const ADD_FILMS_LOADING_SUCCESS = 'ADD_FILMS_LOADING_SUCCESS'
export const FILMS_LOADING = 'FILMS_LOADING'
export const FILMS_LOAD_SUCCESS = 'FILMS_LOAD_SUCCESS'
export const FILMS_LOAD_ERROR = 'FILMS_LOAD_ERROR'

// People
export const ADD_PEOPLE_LOADING = 'ADD_PEOPLE_LOADING'
export const ADD_PEOPLE_LOADING_SUCCESS = 'ADD_PEOPLE_LOADING_SUCCESS'
export const PEOPLE_LOADING = 'PEOPLE_LOADING'
export const PEOPLE_LOAD_SUCCESS = 'PEOPLE_LOAD_SUCCESS'
export const PEOPLE_LOAD_ERROR = 'PEOPLE_LOAD_ERROR'

// homeCards
export const ADD_HOME_CARDS_LOADING = 'ADD_HOME_CARDS_LOADING'
export const ADD_HOME_CARDS_LOADING_SUCCESS = 'ADD_HOME_CARDS_LOADING_SUCCESS'
export const HOME_CARDS_LOADING = 'HOME_CARDS_LOADING'
export const HOME_CARDS_LOAD_SUCCESS = 'HOME_CARDS_LOAD_SUCCESS'
export const HOME_CARDS_LOAD_ERROR = 'HOME_CARDS_LOAD_ERROR'

// errors
export const CONNECTION_ERROR = 'CONNECTION_ERROR'

// search
export const SEARCH_PLANETS = 'SEARCH_PLANETS'
